apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: federation-ingress-gateway
  namespace: istio-system
spec:
  selector:
    istio: eastwestgateway
  servers:
    - port:
        number: 15443
        name: tls
        protocol: TLS
      tls:
        mode: AUTO_PASSTHROUGH
      hosts:
        - "*.local"
    - port:
        number: 8188
        name: https-istiod
        protocol: HTTPS
      tls:
        mode: ISTIO_MUTUAL
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istiod-federation-ingress
  namespace: istio-system
spec:
  hosts:
  - "*"
  gateways:
  - federation-ingress-gateway
  http:
  - route:
    - destination:
        port:
          number: 8188
        host: istiod
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: istiod-federation
  namespace: istio-system
spec:
  host: istiod
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 8188
      tls:
        mode: DISABLE
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-istiod
  namespace: istio-system
spec:
  hosts:
  - istiod.cluster2.local
  addresses:
  - 192.192.192.192/32
  ports:
  - number: 8188
    name: https-istiod
    protocol: HTTPS
  location: MESH_INTERNAL
  resolution: STATIC
  endpoints:
  - address: 172.18.2.1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-istiod-through-egress-gateway
  namespace: istio-system
spec:
  hosts:
  - "*"
  gateways:
  - federation-egress-gateway
  http:
  - match:
    - port: 8188
    route:
    - destination:
        host: istiod.cluster2.local
        port:
          number: 8188
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: federation-egress-gateway
  namespace: istio-system
spec:
  selector:
    istio: egressgateway
  servers:
    - port:
        number: 8188
        name: http-istiod
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-istiod
  namespace: istio-system
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: istiod
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: istiod-federation
  namespace: istio-system
spec:
  host: "istiod.cluster2.local"
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 8188
      tls:
        mode: ISTIO_MUTUAL

# apiVersion: networking.istio.io/v1alpha3
# kind: EnvoyFilter
# metadata:
#   name: istio-multicluster-ingressgateway
#   namespace: istio-system
#   labels:
# spec:
#   workloadSelector:
#     labels:
#       istio: eastwestgateway
#   configPatches:
#   - applyTo: NETWORK_FILTER
#     match:
#       context: GATEWAY
#       listener:
#         portNumber: 15443
#         filterChain:
#           filter:
#             name: "envoy.filters.network.sni_cluster"
#     patch:
#       operation: INSERT_AFTER
#       value:
#         name: "envoy.filters.network.tcp_cluster_rewrite"
#         typed_config:
#           "@type": "type.googleapis.com/istio.envoy.config.filter.network.tcp_cluster_rewrite.v2alpha1.TcpClusterRewrite"
#           cluster_pattern: "\\.federation.local$"
#           cluster_replacement: ".cluster.local"
# ---
# ## To ensure all traffic to globalDomainSuffix is using mTLS
# apiVersion: networking.istio.io/v1alpha3
# kind: DestinationRule
# metadata:
#   name: istio-multicluster-ingressgateway
#   namespace: istio-system
# spec:
#   host: "*.cluster1"
#   trafficPolicy:
#     tls:
#       mode: ISTIO_MUTUAL
